from __future__ import annotations
import typing
from . import polyline
__all__ = ['Bounds', 'Gpx', 'LatLong', 'Segment', 'Track', 'parse', 'polyline']
class Bounds:
    max: LatLong | None
    min: LatLong | None
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, min: LatLong, max: LatLong) -> None:
        ...
    @typing.overload
    def __init__(self, min: tuple[float, float], max: tuple[float, float]) -> None:
        ...
    @typing.overload
    def add(self, location: LatLong) -> None:
        ...
    @typing.overload
    def add(self, bounds: Bounds) -> None:
        ...
    def is_empty(self) -> bool:
        ...
    def is_valid(self) -> bool:
        ...
    def max_bounds(self, bounds: Bounds) -> Bounds:
        ...
    @property
    def max_latitude(self) -> float | None:
        ...
    @max_latitude.setter
    def max_latitude(self, arg1: float) -> None:
        ...
    @property
    def max_longitude(self) -> float | None:
        ...
    @max_longitude.setter
    def max_longitude(self, arg1: float) -> None:
        ...
    @property
    def min_latitude(self) -> float | None:
        ...
    @min_latitude.setter
    def min_latitude(self, arg1: float) -> None:
        ...
    @property
    def min_longitude(self) -> float | None:
        ...
    @min_longitude.setter
    def min_longitude(self, arg1: float) -> None:
        ...
class Gpx:
    tracks: list[Track]
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def bounds(self) -> Bounds:
        ...
    def length_2d(self) -> float:
        ...
    def length_3d(self) -> float:
        ...
class LatLong:
    elevation: float
    latitude: float
    longitude: float
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, latitude: float, longitude: float, elevation: float = 0.0) -> None:
        ...
class Segment:
    points: list[LatLong]
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def bounds(self) -> Bounds:
        ...
    def length_2d(self) -> float:
        ...
    def length_3d(self) -> float:
        ...
class Track:
    comment: str | None
    description: str | None
    name: str | None
    number: int | None
    segments: list[Segment]
    type: str | None
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def bounds(self) -> Bounds:
        ...
    def length_2d(self) -> float:
        ...
    def length_3d(self) -> float:
        ...
def parse(path: str) -> Gpx:
    ...
