name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Choose where to publish"
        required: true
        default: testpypi
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  publish:
    name: Publish to ${{ inputs.repository }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install and setup UV with Python (${{ matrix.python-version }})
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install build tools
        run: |
          uv run --frozen pip install --upgrade pip build twine

      - name: Build package
        run: |
          uv run --frozen build --wheel --sdist

      - name: Upload to TestPyPI
        if: inputs.repository == 'testpypi'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          uv run --frozen twine upload --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Upload to PyPI
        if: inputs.repository == 'pypi'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv run --frozen twine upload dist/*
